---
title: "exercise-2-7"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-2-7}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
```

```{r}
#### The file w_logret_3automanu.txt contains the weekly log returns of three auto manufacturers, General Motors Corp., Ford Motor Corp., and Toyota Motor Corp., from the week of January 3, 1994 to the week of June 25, 2007.

w_logret <- read.table(system.file("extdata", "w_logret_3automanu.txt", package = "dfracs"), header = TRUE)

## a: Write down the sample covariance matrix V^ of these returns.

cov_mat <- cov(w_logret[, -1])
print(cov_mat)

## b: For each pair of these three auto manufacturers, use the result in Exercise 2.6(b) to construct a 95% confidence interval for the correlation coeﬃcient of their returns.

cor_mat <- cor(w_logret[, -1])
print(cor_mat)

p_GM_Ford <- cor_mat["GM", "Ford"]
p_GM_Toyota <- cor_mat["GM", "Toyota"]
p_Ford_Toyota <- cor_mat["Ford", "Toyota"]

n = nrow(w_logret)
cv <- qnorm(0.975)

se_GM_Ford <- (1 - p_GM_Ford^2) / sqrt(n) #result of 2.6: sqrt(n)(p^ - p) → N(0, (1 - p^2)^2).
se_GM_Toyota <- (1 - p_GM_Toyota^2) / sqrt(n)
se_Ford_Toyota <- (1 - p_Ford_Toyota^2) / sqrt(n)

print(c(p_GM_Ford - cv * se_GM_Ford, p_GM_Ford + cv * se_GM_Ford))
print(c(p_GM_Toyota - cv * se_GM_Toyota, p_GM_Toyota + cv * se_GM_Toyota))
print(c(p_Ford_Toyota - cv * se_Ford_Toyota, p_Ford_Toyota + cv * se_Ford_Toyota))

## c: What assumptions have you made for (b)? Perform some graphical checks, such as data plots and Q-Q plots, on these assumptions.
# As stated in 2.6, we let (Ui,Vi) be i.i.d. bivariate normal random vectors to prove sqrt(n)(p^ - p) → N(0, (1 - p^2)^2). We need to assume the pairs of log returns follow a bivariate normal distribution. 

pairs(w_logret[, -1], main = "Returns")

company_names <- c("GM", "Ford", "Toyota")
multiqqplot(w_logret, company_names)
```

