---
title: "exercise-1-5"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-1-5}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
```

```{r}
### The log return of a stock at week t is defined as rt = log(P_t/P_(t-1)), where Pt is the stock price at week t. Consider the weekly log returns of Citigroup Inc., Pfizer Inc., and General Motors from the week of January 4, 1982 to the week of May 21, 2007 in the file w_logret_3stocks.txt.

w_logret <- read.table(system.file("extdata", "w_logret_3stocks.txt", package = "dfracs"), header = TRUE)
w_logret$Date <- as.Date(w_logret$Date, format = "%m/%d/%Y")

##a: Plot the weekly log returns of each stock over time. A widely held assumption in mathematical models of stock prices is that the corresponding log returns are independent and identically distributed (i.i.d.); see Section 3.1. Do your plots show departures from this assumption? 

company_names <- c("Citi", "PFE", "GM")
multiplotlogreturns(w_logret, company_names, "Date", "Weekly")

##b: For each stock, show the Q-Q plot of the weekly log returns and thereby check the assumption that they are normally distributed.

multiqqplot(w_logret, company_names)

##c: For every pair of stocks, estimate the correlation coeﬃcient of the weekly log returns from these data, and give a bootstrap estimate of its standard error.

cor_matrix <- cor(w_logret[, -1])
print(cor_matrix)

k <- 500 
set.seed(1052)
bootstrap_matrix(w_logret[, company_names], k = 500)
```
