---
title: "exercise-1-7"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-1-7}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
```

```{r}
#### The file w_logret_3automanu.txt contains the weekly log returns of three auto manufacturers, General Motors Corp., Ford Motor Corp., and Toyota Motor Corp., from the week of January 3, 1994 to the week of June 25, 2007. Consider the regression model gm = beta_0 + beta_1*toyota + beta_2*ford + e.

w_logret <- read.table(system.file("extdata", "w_logret_3automanu.txt", package = "dfracs"), header = TRUE)
w_logret$Date <- as.Date(w_logret$Date, format = "%m/%d/%Y")

##a: Estimate beta_0, beta_1, and beta_2 by least squares, and give 95% confidence intervals for these parameters.

model <- lm(GM ~ Toyota + Ford, data = w_logret)
summary(model)
confint(model, level = 0.95)

##b: Construct a 95% confidence region for beta = (beta_0,beta_1,beta_2)^T

confreg(model)

##c: Test the null hypothesis beta1 = 0.

summary(model)$coefficients["Toyota", "Pr(>|t|)"]

##d: Check the adequacy of the regression model with plots of the standardized and studentized residuals.

studentized <- rstudent(model)
qqnorm(studentized,
     xlab = "Quantiles of Standard Normal", 
     ylab = "Studentized residuals", 
     pch = 16)
qqline(studentized, lty = 1)

standardized <- rstandard(model)
qqnorm(standardized,
     xlab = "Quantiles of Standard Normal", 
     ylab = "Standardized residuals", 
     pch = 16)
qqline(standardized, lty = 1)

##e: Calculate the leverage and Cook’s distance for each observation. What do these numbers show?

leverage <- hatvalues(model)
cooks_distance <- cooks.distance(model)

plot(leverage, 
     main = "Leverage",
     xlab = "Observations", 
     ylab = "Leverage", 
     pch = 16, cex = 0.75)
abline(h = 2 * mean(leverage), col = "red")

plot(cooks_distance, 
     main = "Cook's Distance",
     xlab = "Observation", 
     ylab = "Cook's Distance",
     pch = 16, cex = 0.75)
abline(h = 4 / nrow(w_logret), col = "red")

##f: Use bootstrapping to estimate the standard errors of the OLS estimates of the regression coeﬃcients. Compare your results with those in (a).

bootstrap_se <- bootstrap_regression(w_logret, GM ~ Toyota + Ford, k = 1000)
bootstrap_se
summary(model)$coefficients[, "Std. Error"]
```

