---
title: "exercise-6-9"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-6-9}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
library(rugarch)
```

```{r}
#### The file sp500_m_logret.txt contains the monthly log returns on the S&P 500 index from the month of January 1950 to the month of June 2007.

sp500_m_logret <- read.table(system.file("extdata", "sp500_m_logret.txt", package = "dfracs"), header = TRUE)

## a: Fit the GARCH(1, 1) model (6.38), in which epsilont are i.i.d. standard normal, to these data. Give standard errors of the estimated parameters.

spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)), mean.model = list(armaOrder = c(0,0), include.mean = TRUE), distribution.model = "norm")

sgarch1_1 <- ugarchfit(spec = spec, data = sp500_m_logret$logret)
show(sgarch1_1)

estimates <- coef(sgarch1_1)
standard_errors <- sqrt(diag(vcov(sgarch1_1)))

df <- data.frame(
  Parameter = names(estimates),
  Estimate = estimates,
  Standard_Error = standard_errors
)

print(df)

## b: Note that even though the sample period is the same as that in Exercise 6.8, a diﬀerent timescale (months) is used here. Compare the results in (a) with those in Exercise 6.8(a), and discuss the implications.

sp500_w_logret <- read.table(system.file("extdata", "sp500_w_logret.txt", package = "dfracs"), header = TRUE)
sp500_w_logret$Date <- as.Date(sp500_w_logret$Date, format = "%m/%d/%Y")

spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)), mean.model = list(armaOrder = c(0,0), include.mean = TRUE), distribution.model = "norm")

sgarch1_1 <- ugarchfit(spec = spec, data = sp500_w_logret$logret)
show(sgarch1_1)

estimates <- coef(sgarch1_1)
standard_errors <- sqrt(diag(vcov(sgarch1_1)))

df <- data.frame(
  Parameter = names(estimates),
  Estimate = estimates,
  Standard_Error = standard_errors
)

print(df)
```
```

