---
title: "exercise-5-7"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-5-7}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
```

```{r}
#### Consider the weekly log returns of Yahoo! stock from the week of April 12, 1996 to the week of June 25, 2007 in the file w logret_yahoo.txt.

w_logret <- read.table(system.file("extdata", "w_logret_yahoo.txt", package = "dfracs"), header = TRUE)
w_logret$Date <- as.Date(w_logret$Date, format = "%m/%d/%Y")

## a: Are there seasonal eﬀects in the series?

plot(logret ~ Date, data = w_logret,
        main = "Yahoo Weekly Log Returns by Month",
        xlab = "Time", ylab = "Log Return")

## b: Are there serial correlations in the series? Use the Ljung-Box statistic Q(10) to perform the test.

Box.test(w_logret$logret, lag = 10, type = "Ljung-Box")

## c: Fit an ARMA(1,1) model to the data from April 12, 1996 to April 30, 2007, and perform diagnostic checks on the fitted model.

dates <- subset(w_logret, Date >= as.Date("1996-04-12") & Date <= as.Date("2007-04-30"))
tmsr <- ts(dates$logret, frequency = 52)

arma_model <- arima(tmsr, order = c(1, 0, 1))
print(summary(arma_model))

Box.test(residuals(arma_model), lag = 10, type = "Ljung-Box")

## d: Compute k-weeks-ahead forecasts (k = 1,2,...,8) based on the fitted model, using April 30, 2007 as the forecast origin. Give the standard errors of your forecasts and compare them with the forecast errors, which are the diﬀerences between the predicted and actual log returns.

real_dates <- subset(w_logret, Date <= as.Date("2007-04-30"))
forcast_dates <- subset(w_logret, Date > as.Date("2007-04-30") & Date <= as.Date("2007-06-25"))

real_ts <- ts(real_dates$logret, frequency = 52)
model <- arima(real_ts, order = c(1, 0, 1))

forecast_result <- predict(model, n.ahead = 8)
predicted <- forecast_result$pred
actual <- forcast_dates$logret
errors <- actual - predicted

data.frame(
  Week = 1:8,
  Forecast = predicted,
  Actual = actual,
  Forecast_Error = errors
)

```

