---
title: "exercise-6-5"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exercise-6-5}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dfracs)
library(rugarch)
```

```{r}
#### The file ibm_w_logret.txt contains the weekly log returns on IBM stock from the week of January 2, 1962 to the week of June 18, 2007. Build a GARCH(1, 1) model with standardized Student-t innovations with v degrees of freedom for the time series, with v also treated as an unknown parameter. Give standard errors of the parameter estimates.

ibm <- read.table(system.file("extdata", "ibm_w_logret.txt", package = "dfracs"), header = TRUE)
ibm$Date <- as.Date(ibm$Date, format = "%m/%d/%Y")

spec <- ugarchspec(variance.model = list(garchOrder = c(1,1)), mean.model = list(armaOrder = c(0,0)), distribution.model = "std")
garch1_1 <- ugarchfit(spec, ibm[, 2])

print(coef(garch1_1))
print((sqrt(diag(vcov(garch1_1)))))
```

